name: Deploy to Vercel VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with: 
          host: 3.91.223.188
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: /home/ubuntu/Prophet-Forecasting-For-Portfolio-Optimisation/scripts/deploy.sh