name: Deploy to AWS instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with: 
          host: 3.91.223.188
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Prophet-Forecasting-For-Portfolio-Optimisation
            git pull origin main
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh